SET IDENTITY_INSERT [dbo].[OfferProducts] ON
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (1, 5, 1)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (2, 21, 1)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (3, 21, 2)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (4, 21, 3)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (5, 24, 3)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (6, 25, 4)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (7, 7, 5)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (8, 4, 6)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (9, 24, 7)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (10, 18, 8)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (11, 18, 9)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (12, 24, 9)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (13, 5, 10)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (14, 24, 10)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (15, 6, 11)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (16, 5, 12)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (17, 9, 13)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (18, 11, 14)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (19, 8, 15)
INSERT INTO [dbo].[OfferProducts] ([Id], [BrandId], [OfferId]) VALUES (20, 16, 16)
SET IDENTITY_INSERT [dbo].[OfferProducts] OFF
