SET IDENTITY_INSERT [dbo].[OfferDetails] ON
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (1, N'6 doses of each product.', CAST(35.0000 AS Money), 1)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (2, N'3 doses of each product', CAST(5.0000 AS Money), 2)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (3, N'6 doses of each product', CAST(15.0000 AS Money), 2)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (4, N'6 doses of each product', CAST(25.0000 AS Money), 3)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (5, N'6 doses of each product', CAST(20.0000 AS Money), 4)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (6, N'12 doses of each product', CAST(45.0000 AS Money), 4)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (7, N'15ml', CAST(10.0000 AS Money), 5)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (8, N'6 doses of each product', CAST(20.0000 AS Money), 6)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (10, N'6 doses of each product', CAST(6.0000 AS Money), 7)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (11, N'12 doses of each product', CAST(15.0000 AS Money), 7)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (12, N'1 collar', CAST(10.0000 AS Money), 8)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (13, N'1 Seresto® collar with 6 doses of Interceptor® Plus (milbemycin oxime/praziquantel)', CAST(20.0000 AS Money), 9)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (14, N'6 doses of each product', CAST(25.0000 AS Money), 10)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (15, N'12 doses of each product', CAST(75.0000 AS Money), 10)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (16, N'30 tablets (20mg)', CAST(15.0000 AS Money), 11)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (17, N'30 tablets (60mg)', CAST(25.0000 AS Money), 11)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (19, N'30 tablets (100mg)', CAST(35.0000 AS Money), 11)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (20, N'90 tablets (20mg)', CAST(45.0000 AS Money), 11)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (21, N'90 tablets (60mg)', CAST(65.0000 AS Money), 11)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (22, N'90 tablets (100mg)', CAST(95.0000 AS Money), 11)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (23, N'3 doses of each product', CAST(5.0000 AS Money), 12)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (24, N'6 doses of each product', CAST(15.0000 AS Money), 12)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (25, N'12 doses of each product', CAST(35.0000 AS Money), 12)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (26, N'30 tablets (12mg)', CAST(15.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (27, N'30 tablets (25mg)', CAST(15.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (28, N'30 tablets (75mg)', CAST(15.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (29, N'30 tablets (100mg)', CAST(15.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (30, N'60 tablets (12mg)', CAST(30.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (31, N'60 tablets (25mg)', CAST(30.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (32, N'60 tablets (25mg)', CAST(30.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (33, N'60 tablets (75mg)', CAST(30.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (34, N'60 tablets (100mg)', CAST(30.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (36, N'90 tablets (12mg)', CAST(45.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (37, N'90 tablets (25mg)', CAST(45.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (38, N'90 tablets (75mg)', CAST(45.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (39, N'90 tablets (100mg)', CAST(45.0000 AS Money), 13)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (40, N'30mL', CAST(25.0000 AS Money), 14)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (41, N'120 tablets (25mg)', CAST(20.0000 AS Money), 15)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (42, N'120 tablets (75mg)', CAST(20.0000 AS Money), 15)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (43, N'120 tablets (100mg)', CAST(20.0000 AS Money), 15)
INSERT INTO [dbo].[OfferDetails] ([Id], [Amount], [Value], [OfferId]) VALUES (44, N'Each product', CAST(5.0000 AS Money), 16)
SET IDENTITY_INSERT [dbo].[OfferDetails] OFF
